export const CHANGE_FIRST_NAME = 'CHANGE_FIRST_NAME';
export const CHANGE_LAST_NAME = 'CHANGE_LAST_NAME';
export const ADD_EMAIL = 'ADD_EMAIL';
export const REMOVE_EMAIL = 'REMOVE_EMAIL';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const SEND_TO_API = 'SEND_TO_API';
export const SEND_TO_API_SUCCESS = 'SEND_TO_API_SUCCESS';
export const SEND_TO_API_FAILED = 'SEND_TO_API_FAILED';
